/* DO NOT EDIT, file generated by nestjs-i18n */
  
/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "validation": {
        "login": {
            "username_empty": string;
            "email_empty": string;
            "password_empty": string;
            "credential_wrong": string;
            "user_inactive": string;
        };
        "Internal Server Error": string;
        "NOT_EMPTY": string;
        "INVALID_EMAIL": string;
        "INVALID_BOOLEAN": string;
        "MIN": string;
        "MAX": string;
        "MAX_LENGTH": string;
        "whitelistValidation": string;
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
